name: Deploy Nightly

on:
  # Run Tuesday through Saturday at 2 AM UTC
  schedule:
    - cron: '0 2 * * 2-6'
  workflow_dispatch:

jobs:
  nightly:
    name: Deploy nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Full history for GoReleaser

      - uses: actions/setup-go@v4
        with:
          go-version: '1.25.1'

      - name: Create nightly tag
        run: |
          TAG="nightly-$(date +'%Y%m%d')"
          echo "NIGHTLY_TAG=$TAG" >> $GITHUB_ENV
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -a "$TAG" -m "Nightly build $TAG"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload nightly release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NIGHTLY_TAG }}
          name: "Nightly Build ${{ env.NIGHTLY_TAG }}"
          prerelease: true
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up old nightly releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 1
          delete_tags: true
          delete_tag_pattern: nightly-
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
